# -*- coding: utf-8 -*-
"""Toilet Affairs_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rInGb4qBGHG7OMspW-03oKjdPQO6ODnL

#**Dependencies**#
"""

import pandas as pd
import numpy as np
import folium

"""#**Scenic Spots**#"""

tourists = pd.read_csv("/content/tourists_with_boundaries_en.csv")

tourists.head()

"""#**Toilets in Taipei**#"""

Taipei_Toilet = pd.read_csv("/content/Taipei_Toilet_new.csv")

Taipei_Toilet.head()

"""#**Haversine Formula**#"""

# Haversine
def haversine(lat1, lon1, lat2, lon2):
    R = 6371000  #radius of Earth in meter
    phi1 = np.radians(lat1)
    phi2 = np.radians(lat2)
    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)
    a = np.sin(delta_phi / 2) ** 2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda / 2) ** 2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    return R * c

# check if all toilets are within 400m
within_range_toilets = []
for _, toilet in Taipei_Toilet.iterrows():
    toilet_lat = toilet['latitude']
    toilet_lon = toilet['longitude']
    within_range = False
    for _, tourist in tourists.iterrows():
        tourist_lat = tourist['Latitude']
        tourist_lon = tourist['Longitude']
        distance = haversine(toilet_lat, toilet_lon, tourist_lat, tourist_lon)
        if distance <= 400:
            within_range = True
            break
    if within_range:
        within_range_toilets.append(toilet)

# toilets  within 400m
within_range_toilets_df = pd.DataFrame(within_range_toilets)

within_range_toilets_df.head()

"""#**Map**#"""

# create a map
map_center = [tourists['Latitude'].mean(), tourists['Longitude'].mean()]
mymap = folium.Map(location=map_center, zoom_start=12)

# circle
for _, row in tourists.iterrows():
    location = [row['Latitude'], row['Longitude']]
    folium.Marker(location, popup=row['Sight'], icon=folium.Icon(color='blue')).add_to(mymap)
    folium.Circle(location, radius=400, color='blue', fill=False).add_to(mymap)

# mark toilets
for _, row in within_range_toilets_df.iterrows():
    location = [row['latitude'], row['longitude']]
    folium.Marker(location, popup=row['name'], icon=folium.Icon(color='green')).add_to(mymap)

mymap

"""#**Save & Download**#"""

# save
mymap.save('final_map_updated.html')

# download
from google.colab import files
files.download('final_map_updated.html')